# This playbook installs Tomcat and Java and is being used to run locally on ec2 instances upon creation in AWS

- hosts: localhost
  remote_user: root
  vars_files:
    -  vars/common.yml

  roles:
    - tomcat
