---
# This Ansible role will download Tomcat from Apache and install on RHEL/CentOS/Ubuntu/Debian and also installs OpenJDK Java
# Alex Knight

- name: Install Java (version specified by variable)
  yum: name=java-1.{{ java_major_version }}.0-openjdk state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install Java (version specified by variable)
  apt: name=openjdk-{{ java_major_version }}-jdk state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Add a tomcat group
  group: name={{ tomcat_group }}

- name: Add a tomcat user
  user: name={{ tomcat_user }} group={{ tomcat_group }} home={{ tomcat_user_home }}

- name: Download Tomcat package
  get_url: url={{ tomcat_url }}/tomcat-{{ tomcat_major_version }}/v{{ tomcat_full_version }}/bin/apache-tomcat-{{ tomcat_full_version }}.tar.gz dest={{ tomcat_dest }}

- name: Extract Tomcat package
  unarchive: src={{ tomcat_dest }}/apache-tomcat-{{ tomcat_full_version }}.tar.gz dest={{ tomcat_dest }} remote_src=True

- name: Create log directory for Tomcat
  file: path={{ tomcat_dest }}/apache-tomcat-{{ tomcat_full_version }}/logs owner={{ tomcat_user }} group={{ tomcat_group }} state=directory

- name: Install Tomcat setenv script
  template: src=setenv.sh dest={{ tomcat_dest }}/apache-tomcat-{{ tomcat_full_version }}/bin/setenv.sh  mode={{ tomcat_setenv_mode }}

- name: Make catalina.sh script executable
  file: path={{ tomcat_dest }}/apache-tomcat-{{ tomcat_full_version }}/bin/catalina.sh mode={{ tomcat_catalina_script_mode }}

- name: Use template tomcat server config
  template: src=server.xml dest={{ tomcat_dest }}/apache-tomcat-{{ tomcat_full_version }}/conf/server.xml

- name: Change ownership of dir
  file: path={{ tomcat_dest }}/apache-tomcat-{{ tomcat_full_version }}  owner=tomcat group=tomcat recurse=yes

- name: Create a symlink dir for Tomcat
  file: src={{ tomcat_dest }}/apache-tomcat-{{ tomcat_full_version }} dest={{ tomcat_symlink }} state=link

- name: Install Tomcat init script
  template: src=tomcat-initscript.sh dest={{ tomcat_init_script_dest }} mode={{ tomcat_init_script_mode }}

- name: Start tomcat
  command: "{{ tomcat_init_script_dest }} start"

- name: Clean up
  file: path={{ tomcat_dest }}/apache-tomcat-{{ tomcat_full_version }}-src.tar.gz state=absent
