---
# This Ansible role will download Tomcat from Apache and install on RHEL/CentOS/Ubuntu/Debian and also installs OpenJDK Java
# Alex Knight

- name: Install Java (version specified by variable)
  yum: name=java-1.{{ java_major_version }}.0-openjdk state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install Java (version specified by variable)
  apt: name=openjdk-{{ java_major_version }}-jdk state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Add a tomcat group
  group: name=tomcat

- name: Add a tomcat user
  user: name=tomcat group=tomcat home=/home/tomcat

- name: Download Tomcat package
  get_url: url={{ tomcat_url }}/tomcat-{{ tomcat_major_version }}/v{{ tomcat_full_version }}/bin/apache-tomcat-{{ tomcat_full_version }}.tar.gz dest=/opt/

- name: Extract Tomcat package
  unarchive: src=/opt/apache-tomcat-{{ tomcat_full_version }}.tar.gz dest=/opt/ remote_src=True

- name: Create log directory for Tomcat
  file: path=/opt/apache-tomcat-{{ tomcat_full_version }}/logs owner=tomcat group=tomcat state=directory

- name: Install Tomcat setenv script
  copy: src=setenv.sh dest=/opt/apache-tomcat-{{ tomcat_full_version }}/bin/setenv.sh  mode=0775

- name: Make catalina.sh script executable
  file: path=/opt/apache-tomcat-{{ tomcat_full_version }}/bin/catalina.sh mode=0775

- name: Change ownership of dir
  file: path=/opt/apache-tomcat-{{ tomcat_full_version }}  owner=tomcat group=tomcat recurse=yes

- name: Create a symlink dir for Tomcat
  file: src=/opt/apache-tomcat-{{ tomcat_full_version }} dest={{ tomcat_symlink }} state=link

- name: Install Tomcat init script
  template: src=tomcat-initscript.sh dest=/etc/init.d/tomcat mode=0755

- name: Start tomcat
  command: /etc/init.d/tomcat start

- name: Clean up
  file: path=/opt/apache-tomcat-{{ tomcat_full_version }}-src.tar.gz state=absent
