---
# This Ansible role will download Tomcat from Apache and install on RHEL/CentOS/Ubuntu/Debian
# Alex Knight

- name: Add a tomcat group
  group: name=tomcat

- name: Add a tomcat user
  user: name=tomcat group=tomcat home=/home/tomcat

- name: Download Tomcat package
  get_url: url={{ tomcat_url }}/tomcat-{{ tomcat_major_version }}/v{{ tomcat_full_version }}/src/apache-tomcat-{{ tomcat_full_version }}-src.tar.gz dest=/opt/

- name: Extract Tomcat package
  unarchive: src=/opt/apache-tomcat-{{ tomcat_full_version }}-src.tar.gz dest=/opt/ remote_src=True

- name: Change ownership of dir
  file: path=/opt/apache-tomcat-{{ tomcat_full_version }}  owner=tomcat group=tomcat recurse=yes

- name: Create a symlink dir for Tomcat
  file: src=/opt/apache-tomcat-{{ tomcat_full_version }}-src dest={{ tomcat_symlink }} state=link

- name: Create log directory for Tomcat
  file: path={{ tomcat_symlink }}/logs owner=tomcat group=tomcat state=directory

- name: Make catalina.sh script executable
  file: path=/opt/tomcat/bin/catalina.sh mode=0775

- name: Install Tomcat init script
  template: src=tomcat-initscript.sh dest=/etc/init.d/tomcat mode=0755

- name: Clean up
  file: path=/opt/apache-tomcat-{{ tomcat_full_version }}-src.tar.gz state=absent
